### ISSUE TITLE
how do I run the makefile without getting error?

### ISSUE THREAD

**Issue by dsl2022** [liamross/appsync-terraform-go-example#1]
Hi, since everything is inside the list-people folder, so the go.mod file is needed to run the make file. It's currently complaining it doesn't find that file even I initialized it inside the list-people folder. could you please share how did you run it?

**Comment by Adron** [comment]
Did you resolve the build error? Could you add you error message here? 

I'm about to run through the code and will see if I can repo it.

**Comment by liamross** [comment]
I personally don't experience any errors when I run `make build`. Essentially all it does is loop through all the folders inside of `./functions` and create a binary for each one inside of `./bin`.

For example, it finds `list-people` folder, and runs the following command:

```console
GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/list-people functions/list-people/main.go
```

This creates the binary `./bin/list-people`.

If the make file isn't working you can always do this manually, I wrote it on a mac so there's potentially some issues with running it on other OS's.
